name: Python application

on: [push]

jobs:
  check-style:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-commas flake8-isort flake8-quotes
    - name: Lint with flake8
      run: |
        flake8

  test-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip "poetry<1.0.0"
        poetry config settings.virtualenvs.create false
        poetry install
    - name: Test with pytest
      run: |
        make coverage

  test-37:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip "poetry<1.0.0"
        poetry config settings.virtualenvs.create false
        poetry install
    - name: Test with pytest
      run: |
        pytest

  test-36:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip "poetry<1.0.0"
        poetry config settings.virtualenvs.create false
        poetry install
    - name: Test with pytest
      run: |
        pytest

  test-35:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip "poetry<1.0.0"
        poetry config settings.virtualenvs.create false
        poetry install
    - name: Test with pytest
      run: |
        pytest
